--- 
abstract: raise the alarum if a source filter was used
author: Shawn M Moore, C<< <sartak at gmail.com> >>
build_requires: 
  Bloom::Filter: 0
  Filter::Simple: 0
  Filter::Util::Call: 0
  Switch: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Acme-Aspartame
no_index: 
  directory: 
    - inc
    - t
version: 0.01
